RSS_SOURCES = [

    # =========================
    # TÜRKİYE
    # =========================

    {
        "id": "trt",
        "name": "TRT Haber",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://www.trthaber.com/sondakika_articles.rss",
    },
    {
        "id": "aa",
        "name": "Anadolu Ajansı",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://www.aa.com.tr/tr/rss/default?cat=guncel",
    },
    {
        "id": "ntv",
        "name": "NTV",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.ntv.com.tr/son-dakika.rss",
    },
    {
        "id": "cnnturk",
        "name": "CNN Türk",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.cnnturk.com/feed/rss/all/news",
    },
    {
        "id": "haberturk",
        "name": "Habertürk",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.haberturk.com/rss",
    },
    {
        "id": "hurriyet",
        "name": "Hürriyet",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://www.hurriyet.com.tr/rss/anasayfa",
    },
    {
        "id": "sozcu",
        "name": "Sözcü",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://www.sozcu.com.tr/feed/",
    },
    {
        "id": "sabah",
        "name": "Sabah",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://www.sabah.com.tr/rss/anasayfa.xml",
    },
    {
        "id": "milliyet",
        "name": "Milliyet",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://www.milliyet.com.tr/rss/rssnew/gundemrss.xml",
    },
    {
        "id": "cumhuriyet",
        "name": "Cumhuriyet",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://www.cumhuriyet.com.tr/rss/son_dakika.xml",
    },
    {
        "id": "t24",
        "name": "T24",
        "country": "tr",
        "language": "tr",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://t24.com.tr/rss",
    },

    # =========================
    # AMERİKA
    # =========================

    {
        "id": "reuters_us",
        "name": "Reuters",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://feeds.reuters.com/reuters/topNews",
    },
    {
        "id": "ap",
        "name": "Associated Press",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://apnews.com/rss",
    },
    {
        "id": "nyt",
        "name": "New York Times",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    },
    {
        "id": "cnn",
        "name": "CNN",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "http://rss.cnn.com/rss/edition.rss",
    },
    {
        "id": "fox",
        "name": "Fox News",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://moxie.foxnews.com/google-publisher/latest.xml",
    },
    {
        "id": "npr",
        "name": "NPR",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://feeds.npr.org/1001/rss.xml",
    },
    {
        "id": "abcnews",
        "name": "ABC News",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://abcnews.go.com/abcnews/topstories",
    },
    {
        "id": "cbsnews",
        "name": "CBS News",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.cbsnews.com/latest/rss/main",
    },
    {
        "id": "usatoday",
        "name": "USA Today",
        "country": "us",
        "language": "en",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://rssfeeds.usatoday.com/usatoday-newstopstories",
    },

    # =========================
    # AVRUPA
    # =========================

    {
        "id": "bbc",
        "name": "BBC",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://feeds.bbci.co.uk/news/rss.xml",
    },
    {
        "id": "guardian",
        "name": "The Guardian",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://www.theguardian.com/world/rss",
    },
    {
        "id": "dw",
        "name": "DW",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://rss.dw.com/rdf/rss-en-all",
    },
    {
        "id": "euronews",
        "name": "Euronews",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.euronews.com/rss",
    },
    {
        "id": "france24",
        "name": "France 24",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.france24.com/en/rss",
    },
    {
        "id": "politico_eu",
        "name": "Politico Europe",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.politico.eu/feed/",
    },
    {
        "id": "euobserver",
        "name": "EUobserver",
        "country": "eu",
        "language": "en",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://euobserver.com/rss.xml",
    },

    # =========================
    # ASYA
    # =========================

    {
        "id": "nhk_world",
        "name": "NHK World",
        "country": "as",
        "language": "en",
        "type": "rss",
        "priority": 5,
        "enabled": True,
        "url": "https://www3.nhk.or.jp/nhkworld/en/news/all.xml",
    },
    {
        "id": "scmp",
        "name": "South China Morning Post",
        "country": "as",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.scmp.com/rss/91/feed",
    },
    {
        "id": "japantimes",
        "name": "The Japan Times",
        "country": "as",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.japantimes.co.jp/feed/",
    },
    {
        "id": "cna",
        "name": "Channel News Asia",
        "country": "as",
        "language": "en",
        "type": "rss",
        "priority": 4,
        "enabled": True,
        "url": "https://www.channelnewsasia.com/rssfeeds/8395986",
    },
    {
        "id": "toi",
        "name": "Times of India",
        "country": "as",
        "language": "en",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    },
    {
        "id": "koreaherald",
        "name": "Korea Herald",
        "country": "as",
        "language": "en",
        "type": "rss",
        "priority": 3,
        "enabled": True,
        "url": "http://www.koreaherald.com/rss/newsAll.xml",
    },
]